$(document).ready(function(){
    // Para mostrar la historia
    $("#item1").click(function(){
        $("#historia").show();
        $("#semestre1").hide();
        $("#semestre2").hide();
        $("#semestre3").hide();
        $("#semestre4").hide();
        $("#semestre5").hide();
        $("#semestre6").hide();
        $("#semestre7").hide();
        $("#semestre8").hide();
        $("#semestre9").hide();
        $("#semestre10").hide();
        $("#perfil").hide();
        $("#saber").hide();        
    })
    // Para mostrar el pensum del semestre 1
    $("#item2").click(function(){
        $("#historia").hide();
        $("#semestre1").show();
        $("#semestre2").hide();
        $("#semestre3").hide();
        $("#semestre4").hide();
        $("#semestre5").hide();
        $("#semestre6").hide();
        $("#semestre7").hide();
        $("#semestre8").hide();
        $("#semestre9").hide();
        $("#semestre10").hide();
        $("#perfil").hide();
        $("#saber").hide();        
    })
    // para mostrar el pensum del semestre 2
    $("#item3").click(function(){
        $("#historia").hide();
        $("#semestre1").hide();
        $("#semestre2").show();
        $("#semestre3").hide();
        $("#semestre4").hide();
        $("#semestre5").hide();
        $("#semestre6").hide();
        $("#semestre7").hide();
        $("#semestre8").hide();
        $("#semestre9").hide();
        $("#semestre10").hide();
        $("#perfil").hide();
        $("#saber").hide();        
    })
    // para mostrar el pensum del semestre 3
    $("#item4").click(function(){
        $("#historia").hide();
        $("#semestre1").hide();
        $("#semestre2").hide();
        $("#semestre3").show();
        $("#semestre4").hide();
        $("#semestre5").hide();
        $("#semestre6").hide();
        $("#semestre7").hide();
        $("#semestre8").hide();
        $("#semestre9").hide();
        $("#semestre10").hide();
        $("#perfil").hide();
        $("#saber").hide();        
    })
    // para mostrar el pensum del semestre 4
    $("#item5").click(function(){
        $("#historia").hide();
        $("#semestre1").hide();
        $("#semestre2").hide();
        $("#semestre3").hide();
        $("#semestre4").show();
        $("#semestre5").hide();
        $("#semestre6").hide();
        $("#semestre7").hide();
        $("#semestre8").hide();
        $("#semestre9").hide();
        $("#semestre10").hide();
        $("#perfil").hide();
        $("#saber").hide();        
    })
    // para mostrar el pensum del semestre 5
    $("#item6").click(function(){
        $("#historia").hide();
        $("#semestre1").hide();
        $("#semestre2").hide();
        $("#semestre3").hide();
        $("#semestre4").hide();
        $("#semestre5").show();
        $("#semestre6").hide();
        $("#semestre7").hide();
        $("#semestre8").hide();
        $("#semestre9").hide();
        $("#semestre10").hide();
        $("#perfil").hide();
        $("#saber").hide();        
    })
    // para mostrar el pensum del semestre 6
    $("#item7").click(function(){
        $("#historia").hide();
        $("#semestre1").hide();
        $("#semestre2").hide();
        $("#semestre3").hide();
        $("#semestre4").hide();
        $("#semestre5").hide();
        $("#semestre6").show();
        $("#semestre7").hide();
        $("#semestre8").hide();
        $("#semestre9").hide();
        $("#semestre10").hide();
        $("#perfil").hide();
        $("#saber").hide();        
    })
    // para mostrar el pensum del semestre 7
    $("#item8").click(function(){
        $("#historia").hide();
        $("#semestre1").hide();
        $("#semestre2").hide();
        $("#semestre3").hide();
        $("#semestre4").hide();
        $("#semestre5").hide();
        $("#semestre6").hide();
        $("#semestre7").show();
        $("#semestre8").hide();
        $("#semestre9").hide();
        $("#semestre10").hide();
        $("#perfil").hide();
        $("#saber").hide();        
    })
    // para mostrar el pensum del semestre 8
    $("#item9").click(function(){
        $("#historia").hide();
        $("#semestre1").hide();
        $("#semestre2").hide();
        $("#semestre3").hide();
        $("#semestre4").hide();
        $("#semestre5").hide();
        $("#semestre6").hide();
        $("#semestre7").hide();
        $("#semestre8").show();
        $("#semestre9").hide();
        $("#semestre10").hide();
        $("#perfil").hide();
        $("#saber").hide();        
    })
    // para mostrar el pensum del semestre 9
    $("#item10").click(function(){
        $("#historia").hide();
        $("#semestre1").hide();
        $("#semestre2").hide();
        $("#semestre3").hide();
        $("#semestre4").hide();
        $("#semestre5").hide();
        $("#semestre6").hide();
        $("#semestre7").hide();
        $("#semestre8").hide();
        $("#semestre9").show();
        $("#semestre10").hide();
        $("#perfil").hide();
        $("#saber").hide();        
    })
    // para mostrar el pensum del semestre 10
    $("#item11").click(function(){
        $("#historia").hide();
        $("#semestre1").hide();
        $("#semestre2").hide();
        $("#semestre3").hide();
        $("#semestre4").hide();
        $("#semestre5").hide();
        $("#semestre6").hide();
        $("#semestre7").hide();
        $("#semestre8").hide();
        $("#semestre9").hide();
        $("#semestre10").show();
        $("#perfil").hide();
        $("#saber").hide();        
    })
    // para mostrar el perfil ocupacional
    $("#item12").click(function(){
        $("#historia").hide();
        $("#semestre1").hide();
        $("#semestre2").hide();
        $("#semestre3").hide();
        $("#semestre4").hide();
        $("#semestre5").hide();
        $("#semestre6").hide();
        $("#semestre7").hide();
        $("#semestre8").hide();
        $("#semestre9").hide();
        $("#semestre10").hide();
        $("#perfil").show();
        $("#saber").hide();        
    })
    // para mostrar las pruebas saber
    $("#item13").click(function(){
        $("#historia").hide();
        $("#semestre1").hide();
        $("#semestre2").hide();
        $("#semestre3").hide();
        $("#semestre4").hide();
        $("#semestre5").hide();
        $("#semestre6").hide();
        $("#semestre7").hide();
        $("#semestre8").hide();
        $("#semestre9").hide();
        $("#semestre10").hide();
        $("#perfil").hide();
        $("#saber").show();        
    })
 
})